package ganteng.hendrawd.footballmatchschedule.network.model

/**
 * @author hendrawd on 09/08/18
 */
data class PlayerNetworkModel(
        val idPlayer: String? = null,
        val idTeam: String? = null,
        val idSoccerXML: String? = null,
        val idPlayerManager: String? = null,
        val strNationality: String? = null,
        val strPlayer: String? = null,
        val strTeam: String? = null,
        val strSport: String? = null,
        val intSoccerXMLTeamID: String? = null,
        val dateBorn: String? = null,
        val dateSigned: String? = null,
        val strSigning: String? = null,
        val strWage: String? = null,
        val strBirthLocation: String? = null,
        val strDescriptionEN: String? = null,
        val strDescriptionDE: String? = null,
        val strDescriptionFR: String? = null,
        val strDescriptionCN: String? = null,
        val strDescriptionIT: String? = null,
        val strDescriptionJP: String? = null,
        val strDescriptionRU: String? = null,
        val strDescriptionES: String? = null,
        val strDescriptionPT: String? = null,
        val strDescriptionSE: String? = null,
        val strDescriptionNL: String? = null,
        val strDescriptionHU: String? = null,
        val strDescriptionNO: String? = null,
        val strDescriptionIL: String? = null,
        val strDescriptionPL: String? = null,
        val strGender: String? = null,
        val strPosition: String? = null,
        val strCollege: String? = null,
        val strFacebook: String? = null,
        val strWebsite: String? = null,
        val strTwitter: String? = null,
        val strInstagram: String? = null,
        val strYoutube: String? = null,
        val strHeight: String? = null,
        val strWeight: String? = null,
        val intLoved: String? = null,
        val strThumb: String? = null,
        val strCutout: String? = null,
        val strBanner: String? = null,
        val strFanart1: String? = null,
        val strFanart2: String? = null,
        val strFanart3: String? = null,
        val strFanart4: String? = null,
        val strLocked: String? = null
)